inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  Exclude:
    # - 'spec/fixtures/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 3.0

plugins:
  - rubocop-rails

# allow method prefix start with "set_" and "get_"
Naming/AccessorMethodName:
  Enabled: false

# allow comment in japanese
Style/AsciiComments:
  Enabled: false

#  allow missing top-level documentation comment of class
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Layout/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - 'test/test_helper.rb'