FROM ruby:3.2.0

RUN apt-get update && \
    apt-get install -y build-essential libpq-dev default-mysql-client nodejs npm && \
    npm install -g yarn && \
    rm -rf /var/lib/apt/lists/*

RUN gem install bundler
WORKDIR /app

# Gemfile準備とbundle install
COPY Gemfile.dev Gemfile
COPY Gemfile.lock* ./
RUN bundle install

# アプリケーションファイルをコピー
COPY . .

# サーバー起動のみ
CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0", "-p", "3000"]
EXPOSE 3000
