version: '3'
services:
  db:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: bm-mysql
    volumes:
      - ./docker/mysql/volumes:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
  app:
    environment:
      - BUCKY_DB_USERNAME=${BUCKY_DB_USERNAME:-root}
      - BUCKY_DB_PASSWORD=${BUCKY_DB_PASSWORD:-password}
      - BUCKY_DB_HOSTNAME=${BUCKY_DB_HOSTNAME:-db}
    depends_on:
      - db