name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the run Docker image
      run: docker-compose up --build -d
    - name: docker ps
      run: docker ps

