name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the run Docker image
      run: |
        export RAILS_ENV=development
        docker-compose up --build -d
    - name: docker ps
      run: docker ps
    - name: BC clone
      run: mkdir /opt/bucky-core && git clone https://github.com/hikimochi/bucky-testing.git /opt/bucky-core
    - name: cd
      run: cd /opt/bucky-core && docker-compose up --build -d && docker ps
    - name: exec
      run: docker exec bucky-core bucky run -D pc -d -l top
    
    


